### ISSUE TITLE
Orbax Checkpointing and Flax.NNX require hacking to work together

### ISSUE THREAD

**Issue by hdrwilkinson** [google/orbax#1337] opened 2024-11-15 13:26 UTC
I'm building a system using `flax.nnx` and `orbax.checkpointing`. However, it is overly complicated on how to save and restore models due to the new `jax.random.key()` being used in `flax.nnx` rather than `jax.random.PRNGkey()`.

I have had to create a workaround where all layers with `rng` and `key` in their path are changed from `dtype=key<fry>` to a format appropriate for saving. Then, upon restoration, they need to be shanged back.

I am attaching a link to a notebook explaining what I've done but I would be keen to hear if there are simpler workarounds? Or, preferably, if there is a way to simple save and restore models?

https://colab.research.google.com/drive/1ozln9ejG7eRtxvbkqHYU3K6OyPvveH9w?usp=sharing

Note: I am also adding an issue to flax to see if there is a fix their side ([#4383](https://github.com/google/flax/issues/4383)).

**Comment by ChromeHearts** [comment] 2024-11-20 18:04
Hi, just checking if https://github.com/google/flax/issues/4383 suggested solution is sufficient enough.  Currently, Orbax only support `dtype=key<fry>` via the [JaxRamdomKeyCheckpointHandler](https://github.com/google/orbax/blob/main/checkpoint/orbax/__init__.py#L68C74-L68C103).  To support it combining with other types, a feature request would be needed.

**Comment by ChromeHearts** [comment] 2024-12-06 20:56
Duplicate of #1105 .  Orbax team is working on supporting RNG as part of a PyTree.

**Closed** 2024-12-06 20:57 UTC
Labels: duplicate
